name: pull from hatenablog

on:
  workflow_dispatch:

jobs:
  pull:
    uses: hatena/hatenablog-workflows/.github/workflows/pull.yaml@819612d4ea1218f10ead435144b1e7c264493127 # v2.0.6
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
