name: pull draft from hatenablog

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Draft Entry Title"
        required: true

jobs:
  pull-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/pull-draft.yaml@819612d4ea1218f10ead435144b1e7c264493127 # v2.0.6
    with:
      title: ${{ github.event.inputs.title }}
      draft: true
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
