name: push published entries


on:
  pull_request:
    paths:
      - "entries/**"

jobs:
  push-published-entries:
    uses: hatena/hatenablog-workflows/.github/workflows/push-published-entries.yaml@819612d4ea1218f10ead435144b1e7c264493127 # v2.0.6
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
