name: push draft to hatena blog

on:
  pull_request:
    paths:
      - "draft_entries/**"

jobs:
  push-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-draft.yaml@819612d4ea1218f10ead435144b1e7c264493127 # v2.0.6
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
