name: push to hatena blog

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "entries/**"

jobs:
  push:
    uses: hatena/hatenablog-workflows/.github/workflows/push.yaml@819612d4ea1218f10ead435144b1e7c264493127 # v2.0.6
    with:
      local_root: "entries"
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
